name: Build Docker Image

on:
  push:
    branches:
      - 'master'
env:
  IMAGE_NAME: shield
  NOTIFICATION_URL: "http://splitscale.systems:3030/notifications"
  NOTIFICATION_INFO: "Build Docker Image"
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
          
      - name: Check Workflow Status
        run: |
            if [[ ${{ success() }} == "true" ]]; then
              curl -X POST -H "Content-Type: application/json" -d '{"title":"'${{ env.IMAGE_NAME }}'","content":{"status":"passed","info":"'${{ env.NOTIFICATION_INFO }}'"}}' ${{ env.NOTIFICATION_URL }}
            else
              curl -X POST -H "Content-Type: application/json" -d '{"title":"'${{ env.IMAGE_NAME }}'","content":{"status":"failed","info":"'${{ env.NOTIFICATION_INFO }}'"}}' ${{ env.NOTIFICATION_URL }}
            fi
