# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  pull_request:
    branches: [ "master" ]
    
env:
  IMAGE_NAME: shield
  NOTIFICATION_URL: "http://splitscale.systems:3030/notifications"
  NOTIFICATION_INFO: "Build and Test"
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: test with Maven
      run: mvn clean test
      
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Check if job suceeded
      if: ${{ success() }}
      run: |
          curl -X POST -H "Content-Type: application/json" -d "{\"title\":\"${{ env.IMAGE_NAME }}\",\"content\":{\"status\":\"passed\",\"info\":\"${{ env.NOTIFICATION_INFO }}\"}}" ${{ env.NOTIFICATION_URL }}
    
    - name: Check if job failed
      if: ${{ failure() }}
      run: |
          curl -X POST -H "Content-Type: application/json" -d "{\"title\":\"${{ env.IMAGE_NAME }}\",\"content\":{\"status\":\"failed\",\"info\":\"${{ env.NOTIFICATION_INFO }}\"}}" ${{ env.NOTIFICATION_URL }}
